Fix symfony 6.3 deprecation warnings in FactoryTrait.php
J-Ben87/ParsleyBundle pull request #23
Opened 2023-12-10 01:38 UTC by pathmissing

Replaces the @required annotation with the corresponding attribute in order to fix symfony 6.3 deprecation warnings.
This change introduces a BC break with PHP installations < 8.0.

2023-12-14 10:32 UTC, J-Ben87 commented
Hi @pathmissing 
Thanks for your contribution!

What would you think if, instead of removing the deprecated `@required` annotation, we added the `#[Required]` attribute?
That way the bundle would remain compatible with older PHP and Symfony versions, and the deprecation wouldn't be a (real) problem anymore.

If you are concerned about having third party deprecations in your project, you may consider setting the relevant env variable to `SYMFONY_DEPRECATIONS_HELPER=max[direct]=0&quiet[]=indirect&quiet[]=other`.

2023-12-14 10:36 UTC, J-Ben87 requested changes

2023-12-14 10:36 UTC, J-Ben87 commented on src/Constraint/Factory/FactoryTrait.php
> +    #[Required]
Something like that:
```suggestion
    /**
     * @required
     */
    #[Required]
```

2023-12-14 21:20 UTC, pathmissing commented
Sounds good to me 👍

2023-12-15 09:18 UTC, J-Ben87 approved these changes

2023-12-15 09:18 UTC, merged

2023-12-15 09:18 UTC, J-Ben87 commented
Amazing, thanks! 👍🏻